/* c5c4d8d2c97188776469c20f13310277b5051200
 * This file is automatically generated by graphql-let. */

export declare type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const PaginatorPartsFragmentDoc: import("@apollo/client").DocumentNode;