/* dec764f630ebd04f9e61a74d7634347116f1642f
 * This file is automatically generated by graphql-let. */

export declare type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const PaginatorPartsFragmentDoc: import("@apollo/client").DocumentNode;