/* 07b2dc60735914505c1549693adde043bdf4bb69
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
export declare type ProductPartsFragment = {
  __typename?: 'Product';
  id: string;
  name: string;
  slug: string;
  product_type: Types.ProductType;
  price?: number | null | undefined;
  sale_price?: number | null | undefined;
  min_price?: number | null | undefined;
  max_price?: number | null | undefined;
  quantity: number;
  unit: string;
  type: {
    __typename?: 'Type';
    id: string;
    name: string;
    slug: string;
    settings?: {
      __typename?: 'TypeSettings';
      productCard: string;
    } | null | undefined;
  };
};
export declare const ProductPartsFragmentDoc: import("@apollo/client").DocumentNode;