/* 01111b6f6c1f8e569854160ac6326dd1423bf850
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export declare type OrderPartsFragment = {
  __typename?: 'Order';
  id: string;
  tracking_number: string;
  customer_contact: string;
  amount: number;
  sales_tax: number;
  total: number;
  paid_total: number;
  payment_id?: string | null | undefined;
  payment_gateway: Types.PaymentGatewayType;
  discount?: number | null | undefined;
  delivery_fee: number;
  delivery_time: string;
  created_at: any;
  updated_at: any;
  customer: {
    __typename?: 'User';
    name: string;
  };
  status: {
    __typename?: 'OrderStatus';
    id: string;
    name: string;
    color: string;
    serial: number;
  };
  products: Array<{
    __typename?: 'Product';
    name: string;
    price?: number | null | undefined;
    sale_price?: number | null | undefined;
    created_at: any;
    quantity: number;
    unit: string;
    image?: {
      __typename?: 'Attachment';
      id?: string | null | undefined;
      original?: string | null | undefined;
      thumbnail?: string | null | undefined;
    } | null | undefined;
    variation_options?: Array<{
      __typename?: 'Variation';
      id: string;
      title: string;
    }> | null | undefined;
    pivot?: {
      __typename?: 'OrderProductPivot';
      variation_option_id?: string | null | undefined;
      order_quantity: number;
      unit_price: number;
      subtotal: number;
    } | null | undefined;
  }>;
  coupon?: {
    __typename?: 'Coupon';
    code: string;
    amount: number;
    type: Types.CouponType;
    id: string;
  } | null | undefined;
  billing_address: {
    __typename?: 'UserAddress';
    country: string;
    city: string;
    state: string;
    zip: string;
    street_address: string;
  };
  shipping_address: {
    __typename?: 'UserAddress';
    country: string;
    city: string;
    state: string;
    zip: string;
    street_address: string;
  };
  refund?: {
    __typename?: 'Refund';
    id: string;
    title: string;
    amount: string;
    status?: Types.RefundStatus | null | undefined;
  } | null | undefined;
  wallet_point?: {
    __typename?: 'WalletPoint';
    id: string;
    amount: number;
  } | null | undefined;
};
export declare type OrdersQueryVariables = Types.Exact<{
  tracking_number?: Types.Maybe<Types.Scalars['String']>;
  orderBy?: Types.Maybe<Types.Scalars['String']>;
  sortedBy?: Types.Maybe<Types.Scalars['String']>;
  customer_id?: Types.Maybe<Types.Scalars['ID']>;
  shop_id?: Types.Maybe<Types.Scalars['ID']>;
  first?: Types.Maybe<Types.Scalars['Int']>;
  page?: Types.Maybe<Types.Scalars['Int']>;
}>;
export declare type OrdersQuery = {
  __typename?: 'Query';
  orders: {
    __typename?: 'OrderPaginator';
    data: Array<{
      __typename?: 'Order';
      id: string;
      tracking_number: string;
      customer_contact: string;
      amount: number;
      sales_tax: number;
      total: number;
      paid_total: number;
      payment_id?: string | null | undefined;
      payment_gateway: Types.PaymentGatewayType;
      discount?: number | null | undefined;
      delivery_fee: number;
      delivery_time: string;
      created_at: any;
      updated_at: any;
      customer: {
        __typename?: 'User';
        name: string;
      };
      status: {
        __typename?: 'OrderStatus';
        id: string;
        name: string;
        color: string;
        serial: number;
      };
      products: Array<{
        __typename?: 'Product';
        name: string;
        price?: number | null | undefined;
        sale_price?: number | null | undefined;
        created_at: any;
        quantity: number;
        unit: string;
        image?: {
          __typename?: 'Attachment';
          id?: string | null | undefined;
          original?: string | null | undefined;
          thumbnail?: string | null | undefined;
        } | null | undefined;
        variation_options?: Array<{
          __typename?: 'Variation';
          id: string;
          title: string;
        }> | null | undefined;
        pivot?: {
          __typename?: 'OrderProductPivot';
          variation_option_id?: string | null | undefined;
          order_quantity: number;
          unit_price: number;
          subtotal: number;
        } | null | undefined;
      }>;
      coupon?: {
        __typename?: 'Coupon';
        code: string;
        amount: number;
        type: Types.CouponType;
        id: string;
      } | null | undefined;
      billing_address: {
        __typename?: 'UserAddress';
        country: string;
        city: string;
        state: string;
        zip: string;
        street_address: string;
      };
      shipping_address: {
        __typename?: 'UserAddress';
        country: string;
        city: string;
        state: string;
        zip: string;
        street_address: string;
      };
      refund?: {
        __typename?: 'Refund';
        id: string;
        title: string;
        amount: string;
        status?: Types.RefundStatus | null | undefined;
      } | null | undefined;
      wallet_point?: {
        __typename?: 'WalletPoint';
        id: string;
        amount: number;
      } | null | undefined;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export declare type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare type OrderQueryVariables = Types.Exact<{
  tracking_number?: Types.Maybe<Types.Scalars['String']>;
  id?: Types.Maybe<Types.Scalars['ID']>;
}>;
export declare type OrderQuery = {
  __typename?: 'Query';
  order: {
    __typename?: 'Order';
    id: string;
    tracking_number: string;
    customer_contact: string;
    amount: number;
    sales_tax: number;
    total: number;
    paid_total: number;
    payment_id?: string | null | undefined;
    payment_gateway: Types.PaymentGatewayType;
    discount?: number | null | undefined;
    delivery_fee: number;
    delivery_time: string;
    created_at: any;
    updated_at: any;
    children: Array<{
      __typename?: 'Order';
      id: string;
      tracking_number: string;
      customer_contact: string;
      amount: number;
      sales_tax: number;
      total: number;
      paid_total: number;
      payment_id?: string | null | undefined;
      payment_gateway: Types.PaymentGatewayType;
      discount?: number | null | undefined;
      delivery_fee: number;
      delivery_time: string;
      created_at: any;
      updated_at: any;
      customer: {
        __typename?: 'User';
        name: string;
      };
      status: {
        __typename?: 'OrderStatus';
        id: string;
        name: string;
        color: string;
        serial: number;
      };
      products: Array<{
        __typename?: 'Product';
        name: string;
        price?: number | null | undefined;
        sale_price?: number | null | undefined;
        created_at: any;
        quantity: number;
        unit: string;
        image?: {
          __typename?: 'Attachment';
          id?: string | null | undefined;
          original?: string | null | undefined;
          thumbnail?: string | null | undefined;
        } | null | undefined;
        variation_options?: Array<{
          __typename?: 'Variation';
          id: string;
          title: string;
        }> | null | undefined;
        pivot?: {
          __typename?: 'OrderProductPivot';
          variation_option_id?: string | null | undefined;
          order_quantity: number;
          unit_price: number;
          subtotal: number;
        } | null | undefined;
      }>;
      coupon?: {
        __typename?: 'Coupon';
        code: string;
        amount: number;
        type: Types.CouponType;
        id: string;
      } | null | undefined;
      billing_address: {
        __typename?: 'UserAddress';
        country: string;
        city: string;
        state: string;
        zip: string;
        street_address: string;
      };
      shipping_address: {
        __typename?: 'UserAddress';
        country: string;
        city: string;
        state: string;
        zip: string;
        street_address: string;
      };
      refund?: {
        __typename?: 'Refund';
        id: string;
        title: string;
        amount: string;
        status?: Types.RefundStatus | null | undefined;
      } | null | undefined;
      wallet_point?: {
        __typename?: 'WalletPoint';
        id: string;
        amount: number;
      } | null | undefined;
    }>;
    customer: {
      __typename?: 'User';
      name: string;
    };
    status: {
      __typename?: 'OrderStatus';
      id: string;
      name: string;
      color: string;
      serial: number;
    };
    products: Array<{
      __typename?: 'Product';
      name: string;
      price?: number | null | undefined;
      sale_price?: number | null | undefined;
      created_at: any;
      quantity: number;
      unit: string;
      image?: {
        __typename?: 'Attachment';
        id?: string | null | undefined;
        original?: string | null | undefined;
        thumbnail?: string | null | undefined;
      } | null | undefined;
      variation_options?: Array<{
        __typename?: 'Variation';
        id: string;
        title: string;
      }> | null | undefined;
      pivot?: {
        __typename?: 'OrderProductPivot';
        variation_option_id?: string | null | undefined;
        order_quantity: number;
        unit_price: number;
        subtotal: number;
      } | null | undefined;
    }>;
    coupon?: {
      __typename?: 'Coupon';
      code: string;
      amount: number;
      type: Types.CouponType;
      id: string;
    } | null | undefined;
    billing_address: {
      __typename?: 'UserAddress';
      country: string;
      city: string;
      state: string;
      zip: string;
      street_address: string;
    };
    shipping_address: {
      __typename?: 'UserAddress';
      country: string;
      city: string;
      state: string;
      zip: string;
      street_address: string;
    };
    refund?: {
      __typename?: 'Refund';
      id: string;
      title: string;
      amount: string;
      status?: Types.RefundStatus | null | undefined;
    } | null | undefined;
    wallet_point?: {
      __typename?: 'WalletPoint';
      id: string;
      amount: number;
    } | null | undefined;
  };
};
export declare type CreateOrderMutationVariables = Types.Exact<{
  input: Types.CreateOrderInput;
}>;
export declare type CreateOrderMutation = {
  __typename?: 'Mutation';
  createOrder: {
    __typename?: 'Order';
    id: string;
    tracking_number: string;
    customer_contact: string;
    amount: number;
    sales_tax: number;
    total: number;
    paid_total: number;
    payment_id?: string | null | undefined;
    payment_gateway: Types.PaymentGatewayType;
    discount?: number | null | undefined;
    delivery_fee: number;
    delivery_time: string;
    created_at: any;
    updated_at: any;
    customer: {
      __typename?: 'User';
      name: string;
    };
    status: {
      __typename?: 'OrderStatus';
      id: string;
      name: string;
      color: string;
      serial: number;
    };
    products: Array<{
      __typename?: 'Product';
      name: string;
      price?: number | null | undefined;
      sale_price?: number | null | undefined;
      created_at: any;
      quantity: number;
      unit: string;
      image?: {
        __typename?: 'Attachment';
        id?: string | null | undefined;
        original?: string | null | undefined;
        thumbnail?: string | null | undefined;
      } | null | undefined;
      variation_options?: Array<{
        __typename?: 'Variation';
        id: string;
        title: string;
      }> | null | undefined;
      pivot?: {
        __typename?: 'OrderProductPivot';
        variation_option_id?: string | null | undefined;
        order_quantity: number;
        unit_price: number;
        subtotal: number;
      } | null | undefined;
    }>;
    coupon?: {
      __typename?: 'Coupon';
      code: string;
      amount: number;
      type: Types.CouponType;
      id: string;
    } | null | undefined;
    billing_address: {
      __typename?: 'UserAddress';
      country: string;
      city: string;
      state: string;
      zip: string;
      street_address: string;
    };
    shipping_address: {
      __typename?: 'UserAddress';
      country: string;
      city: string;
      state: string;
      zip: string;
      street_address: string;
    };
    refund?: {
      __typename?: 'Refund';
      id: string;
      title: string;
      amount: string;
      status?: Types.RefundStatus | null | undefined;
    } | null | undefined;
    wallet_point?: {
      __typename?: 'WalletPoint';
      id: string;
      amount: number;
    } | null | undefined;
  };
};
export declare type OrderStatusesQueryVariables = Types.Exact<{
  first?: Types.Maybe<Types.Scalars['Int']>;
  page?: Types.Maybe<Types.Scalars['Int']>;
  text?: Types.Maybe<Types.Scalars['String']>;
  orderBy?: Types.Maybe<Array<Types.QueryOrderStatusesOrderByOrderByClause> | Types.QueryOrderStatusesOrderByOrderByClause>;
}>;
export declare type OrderStatusesQuery = {
  __typename?: 'Query';
  orderStatuses: {
    __typename?: 'OrderStatusPaginator';
    data: Array<{
      __typename?: 'OrderStatus';
      id: string;
      name: string;
      color: string;
      serial: number;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      perPage: number;
      total: number;
      lastPage: number;
      count: number;
    };
  };
};
export declare const OrderPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const OrdersDocument: Apollo.DocumentNode;
/**
 * __useOrdersQuery__
 *
 * To run a query within a React component, call `useOrdersQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrdersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrdersQuery({
 *   variables: {
 *      tracking_number: // value for 'tracking_number'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      customer_id: // value for 'customer_id'
 *      shop_id: // value for 'shop_id'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */

export declare function useOrdersQuery(baseOptions?: Apollo.QueryHookOptions<OrdersQuery, OrdersQueryVariables>): Apollo.QueryResult<OrdersQuery, Types.Exact<{
  tracking_number?: Types.Maybe<string> | undefined;
  orderBy?: Types.Maybe<string> | undefined;
  sortedBy?: Types.Maybe<string> | undefined;
  customer_id?: Types.Maybe<string> | undefined;
  shop_id?: Types.Maybe<string> | undefined;
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
}>>;
export declare function useOrdersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrdersQuery, OrdersQueryVariables>): Apollo.QueryTuple<OrdersQuery, Types.Exact<{
  tracking_number?: Types.Maybe<string> | undefined;
  orderBy?: Types.Maybe<string> | undefined;
  sortedBy?: Types.Maybe<string> | undefined;
  customer_id?: Types.Maybe<string> | undefined;
  shop_id?: Types.Maybe<string> | undefined;
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
}>>;
export declare type OrdersQueryHookResult = ReturnType<typeof useOrdersQuery>;
export declare type OrdersLazyQueryHookResult = ReturnType<typeof useOrdersLazyQuery>;
export declare type OrdersQueryResult = Apollo.QueryResult<OrdersQuery, OrdersQueryVariables>;
export declare const OrderDocument: Apollo.DocumentNode;
/**
 * __useOrderQuery__
 *
 * To run a query within a React component, call `useOrderQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrderQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrderQuery({
 *   variables: {
 *      tracking_number: // value for 'tracking_number'
 *      id: // value for 'id'
 *   },
 * });
 */

export declare function useOrderQuery(baseOptions?: Apollo.QueryHookOptions<OrderQuery, OrderQueryVariables>): Apollo.QueryResult<OrderQuery, Types.Exact<{
  tracking_number?: Types.Maybe<string> | undefined;
  id?: Types.Maybe<string> | undefined;
}>>;
export declare function useOrderLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrderQuery, OrderQueryVariables>): Apollo.QueryTuple<OrderQuery, Types.Exact<{
  tracking_number?: Types.Maybe<string> | undefined;
  id?: Types.Maybe<string> | undefined;
}>>;
export declare type OrderQueryHookResult = ReturnType<typeof useOrderQuery>;
export declare type OrderLazyQueryHookResult = ReturnType<typeof useOrderLazyQuery>;
export declare type OrderQueryResult = Apollo.QueryResult<OrderQuery, OrderQueryVariables>;
export declare const CreateOrderDocument: Apollo.DocumentNode;
export declare type CreateOrderMutationFn = Apollo.MutationFunction<CreateOrderMutation, CreateOrderMutationVariables>;
/**
 * __useCreateOrderMutation__
 *
 * To run a mutation, you first call `useCreateOrderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateOrderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createOrderMutation, { data, loading, error }] = useCreateOrderMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */

export declare function useCreateOrderMutation(baseOptions?: Apollo.MutationHookOptions<CreateOrderMutation, CreateOrderMutationVariables>): Apollo.MutationTuple<CreateOrderMutation, Types.Exact<{
  input: Types.CreateOrderInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export declare type CreateOrderMutationHookResult = ReturnType<typeof useCreateOrderMutation>;
export declare type CreateOrderMutationResult = Apollo.MutationResult<CreateOrderMutation>;
export declare type CreateOrderMutationOptions = Apollo.BaseMutationOptions<CreateOrderMutation, CreateOrderMutationVariables>;
export declare const OrderStatusesDocument: Apollo.DocumentNode;
/**
 * __useOrderStatusesQuery__
 *
 * To run a query within a React component, call `useOrderStatusesQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrderStatusesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrderStatusesQuery({
 *   variables: {
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      text: // value for 'text'
 *      orderBy: // value for 'orderBy'
 *   },
 * });
 */

export declare function useOrderStatusesQuery(baseOptions?: Apollo.QueryHookOptions<OrderStatusesQuery, OrderStatusesQueryVariables>): Apollo.QueryResult<OrderStatusesQuery, Types.Exact<{
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
  text?: Types.Maybe<string> | undefined;
  orderBy?: Types.Maybe<Types.QueryOrderStatusesOrderByOrderByClause | Types.QueryOrderStatusesOrderByOrderByClause[]> | undefined;
}>>;
export declare function useOrderStatusesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrderStatusesQuery, OrderStatusesQueryVariables>): Apollo.QueryTuple<OrderStatusesQuery, Types.Exact<{
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
  text?: Types.Maybe<string> | undefined;
  orderBy?: Types.Maybe<Types.QueryOrderStatusesOrderByOrderByClause | Types.QueryOrderStatusesOrderByOrderByClause[]> | undefined;
}>>;
export declare type OrderStatusesQueryHookResult = ReturnType<typeof useOrderStatusesQuery>;
export declare type OrderStatusesLazyQueryHookResult = ReturnType<typeof useOrderStatusesLazyQuery>;
export declare type OrderStatusesQueryResult = Apollo.QueryResult<OrderStatusesQuery, OrderStatusesQueryVariables>;