/* be603fc4db850cf343648ce6ed5fa2c4984d8534
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export declare type CategoryPartsFragment = {
  __typename?: 'Category';
  id: string;
  name: string;
  slug: string;
  details?: string | null | undefined;
  parent_id?: string | null | undefined;
  products_count?: number | null | undefined;
  icon?: string | null | undefined;
  image?: {
    __typename?: 'Attachment';
    id?: string | null | undefined;
    original?: string | null | undefined;
    thumbnail?: string | null | undefined;
  } | null | undefined;
  type?: {
    __typename?: 'Type';
    id: string;
    name: string;
    slug: string;
  } | null | undefined;
};
export declare type CategoriesQueryVariables = Types.Exact<{
  orderBy?: Types.Maybe<Array<Types.QueryCategoriesOrderByOrderByClause> | Types.QueryCategoriesOrderByOrderByClause>;
  hasType?: Types.Maybe<Types.QueryCategoriesHasTypeWhereHasConditions>;
  name?: Types.Maybe<Types.Scalars['String']>;
  first?: Types.Maybe<Types.Scalars['Int']>;
  page?: Types.Maybe<Types.Scalars['Int']>;
  parent?: Types.Maybe<Types.Scalars['ID']>;
}>;
export declare type CategoriesQuery = {
  __typename?: 'Query';
  categories: {
    __typename?: 'CategoryPaginator';
    data: Array<{
      __typename?: 'Category';
      id: string;
      name: string;
      slug: string;
      details?: string | null | undefined;
      parent_id?: string | null | undefined;
      products_count?: number | null | undefined;
      icon?: string | null | undefined;
      children?: Array<{
        __typename?: 'Category';
        id: string;
        name: string;
        slug: string;
        details?: string | null | undefined;
        parent_id?: string | null | undefined;
        products_count?: number | null | undefined;
        icon?: string | null | undefined;
        children?: Array<{
          __typename?: 'Category';
          id: string;
          name: string;
          slug: string;
          details?: string | null | undefined;
          parent_id?: string | null | undefined;
          products_count?: number | null | undefined;
          icon?: string | null | undefined;
          image?: {
            __typename?: 'Attachment';
            id?: string | null | undefined;
            original?: string | null | undefined;
            thumbnail?: string | null | undefined;
          } | null | undefined;
          type?: {
            __typename?: 'Type';
            id: string;
            name: string;
            slug: string;
          } | null | undefined;
        }> | null | undefined;
        image?: {
          __typename?: 'Attachment';
          id?: string | null | undefined;
          original?: string | null | undefined;
          thumbnail?: string | null | undefined;
        } | null | undefined;
        type?: {
          __typename?: 'Type';
          id: string;
          name: string;
          slug: string;
        } | null | undefined;
      }> | null | undefined;
      image?: {
        __typename?: 'Attachment';
        id?: string | null | undefined;
        original?: string | null | undefined;
        thumbnail?: string | null | undefined;
      } | null | undefined;
      type?: {
        __typename?: 'Type';
        id: string;
        name: string;
        slug: string;
      } | null | undefined;
    }>;
  };
};
export declare const CategoryPartsFragmentDoc: Apollo.DocumentNode;
export declare const CategoriesDocument: Apollo.DocumentNode;
/**
 * __useCategoriesQuery__
 *
 * To run a query within a React component, call `useCategoriesQuery` and pass it any options that fit your needs.
 * When your component renders, `useCategoriesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCategoriesQuery({
 *   variables: {
 *      orderBy: // value for 'orderBy'
 *      hasType: // value for 'hasType'
 *      name: // value for 'name'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      parent: // value for 'parent'
 *   },
 * });
 */

export declare function useCategoriesQuery(baseOptions?: Apollo.QueryHookOptions<CategoriesQuery, CategoriesQueryVariables>): Apollo.QueryResult<CategoriesQuery, Types.Exact<{
  orderBy?: Types.Maybe<Types.QueryCategoriesOrderByOrderByClause | Types.QueryCategoriesOrderByOrderByClause[]> | undefined;
  hasType?: Types.Maybe<Types.QueryCategoriesHasTypeWhereHasConditions> | undefined;
  name?: Types.Maybe<string> | undefined;
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
  parent?: Types.Maybe<string> | undefined;
}>>;
export declare function useCategoriesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CategoriesQuery, CategoriesQueryVariables>): Apollo.QueryTuple<CategoriesQuery, Types.Exact<{
  orderBy?: Types.Maybe<Types.QueryCategoriesOrderByOrderByClause | Types.QueryCategoriesOrderByOrderByClause[]> | undefined;
  hasType?: Types.Maybe<Types.QueryCategoriesHasTypeWhereHasConditions> | undefined;
  name?: Types.Maybe<string> | undefined;
  first?: Types.Maybe<number> | undefined;
  page?: Types.Maybe<number> | undefined;
  parent?: Types.Maybe<string> | undefined;
}>>;
export declare type CategoriesQueryHookResult = ReturnType<typeof useCategoriesQuery>;
export declare type CategoriesLazyQueryHookResult = ReturnType<typeof useCategoriesLazyQuery>;
export declare type CategoriesQueryResult = Apollo.QueryResult<CategoriesQuery, CategoriesQueryVariables>;